title: Python for loop
hero_image: images/banner.png
description: How for loops work in Python
original_url:
duration: 1
ingredient: true
technologies: "python"
theme: cc-prototype
listed: false
copyedit: false
interests: ""
steps:
  - title: For loop

