title: Python for loop
hero_image: images/banner.png
description: How `for` loops work in Python
original_url: 
ingredient: true
technologies: "python"
theme: cc-prototype
published: false
steps:
  - title: For loop
    duration: 1
